name: result_option
description: The types that represent the result of the operation. this is useful when designing API requires that an user should handle errors explicitly. 
version: 1.0.0
repository: https://github.com/pubmskim/result_option

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  to_string_pretty: ^1.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
